### ISSUE TITLE
omnitrace-avail fails with GFXIP is not supported(gfx90c)

### ISSUE THREAD

**Issue by benrichard-amd** [ROCm/omnitrace#332]
This seems to be an issue in rocprof. Is there a way omnitrace-avail can ignore this error from rocprof? On this machine I am unable to disable the unsupported GPU, so the supported GPU (Navi2) does not get detected.

```
$ omnitrace-avail
[omnitrace][4043][0][fatal] 
[omnitrace][4043][0][fatal] ERROR :: rocprofiler_iterate_info(), Translate(), ImportMetrics: bad block name 'GRBM', GFXIP is not supported(gfx90c)


```

**Comment by jrmadsen** [comment]
You can use the environment variable `ROCR_VISIBLE_DEVICES` to hide that device in the HSA runtime — which will cause rocprof and Omnitrace to not see that device when they iterate over the available HSA agents.
